apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {

        upstream pod {
            server 10.42.1.104:8080;
        }

        upstream svc {
            server 10.43.218.107:8080;
        }

        server {
            listen       80;
            server_name  localhost;

            location / {
              root /usr/share/nginx/html;
            }

            location /pod {
              proxy_pass       http://pod;
            }

            location /svc {
              proxy_pass       http://svc;
            }
        }
    }
