apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: conf
        configMap:
          name: nginx-conf
      terminationGracePeriodSeconds: 2
      containers:
      - name: nginx
        # It runs the app.py script, which implemented a HTTP service listenning 8000 port
        image: registry:5000/nginx:1.23.3-alpine
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        ports:
        - containerPort: 80
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
