apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: server
  sessionAffinity: None
  type: ClusterIP