apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 6
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: server
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: server
        # It runs the app.py script, which implemented a HTTP service listenning 8000 port
        image: registry:5000/delayed-openresty-server:0.0.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
        ports:
        - containerPort: 80
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exit
            - "0"
          initialDelaySeconds: 5
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep
              - "10"
